apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-data
  namespace: {{ .Values.namespace.name | default "todoapp" }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.pv.storage | default "1Gi" }}
  hostPath:
    path: /data/
