
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-data
  namespace: {{ .Values.namespace.name }}
spec:
  volumeName: {{ .Chart.Name }}-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.requests.storage }}